apiVersion: batch/v1
kind: Job
metadata:
  name: hello-test
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.8.0
          command: ["sh", "-c", "curl -s http://hello-service && echo SUCCESS"]
      restartPolicy: Never
  backoffLimit: 1
