name: Run integration tests

on:
  push: #TODO for test purpose. change to main only
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "integration-tests"
  cancel-in-progress: false

jobs:
  integration-tests:
    environment:
      name: pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up Kind
#        uses: helm/kind-action@v1.12.0
#        with:
#          cluster_name: kind

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

#      - name: Checkout cloud core bootstrap repo
#        uses: actions/checkout@v4
#        with:
#          repository: Netcracker/qubership-core-bootstrap
#          path: core-bootstrap-repo
#
#      - name: Deploy cloud core
#        run: make -C core-bootstrap-repo/cloud-core-local-dev/ install

      - name: Run integration tests
        run: mvn clean test surefire-report:report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Update report history
        run: |
          mkdir -p report
          history_file="report/history.json"
          [ -f "$history_file" ] || echo "{}" > "$history_file"
          
          today=$(date -u +"%Y-%m-%d")
          day_dir="report/$today"
          mkdir -p "$day_dir"
          cp -r target/surefire-reports/* "$day_dir/"
          
          # Parse XML reports
          successes=0
          failures=0
          for f in target/surefire-reports/TEST-*.xml; do
            [ -f "$f" ] || continue
            run=$(xmllint --xpath "number(//testsuite/@tests)" "$f" 2>/dev/null || echo 0)
            fail=$(xmllint --xpath "number(//testsuite/@failures)" "$f" 2>/dev/null || echo 0)
            error=$(xmllint --xpath "number(//testsuite/@errors)" "$f" 2>/dev/null || echo 0)
            successes=$((successes + run - fail - error))
            failures=$((failures + fail + error))
          done
          
          status="success"
          [ "$failures" -gt 0 ] && status="failure"
          
          tmpfile=$(mktemp)
          cp "$history_file" "$tmpfile"
          jq --arg day "$today" --arg status "$status" \
             --argjson successes "$successes" --argjson failures "$failures" \
             --arg path "$today" '.[$day]={status:$status,successes:$successes,failures:$failures,path:$path}' \
             "$tmpfile" > "$tmpfile.new"
          mv "$tmpfile.new" "$history_file"

      - name: Copy HTML template
        run: cp report-template.html report/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report