name: Run integration tests

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "integration-tests"
  cancel-in-progress: false

jobs:
  integration-tests:
    environment:
      name: pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run integration tests for all modules
        run: mvn -B clean surefire-report:report || true

      - name: Upload Surefire reports
        run: |
          for module in $(find . -maxdepth 1 -type d ! -name . ! -name report); do
            if [ -d "$module/target/surefire-reports" ] || [ -d "$module/target/reports" ]; then
              modname=$(basename "$module")
              echo "Uploading reports for $modname"
              tar -czf "$modname-reports.tgz" \
                "$module/target/surefire-reports" \
                "$module/target/reports" 2>/dev/null || true
              gh run upload-artifact --name "surefire-reports-$modname" "$modname-reports.tgz"
            fi
          done