name: Run integration tests

on:
  push: #TODO for test purpose. change to main only
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "integration-tests"
  cancel-in-progress: false

jobs:
  integration-tests:
    environment:
      name: integration-tests
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up Kind
#        uses: helm/kind-action@v1.12.0
#        with:
#          cluster_name: kind

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

#      - name: Checkout cloud core bootstrap repo
#        uses: actions/checkout@v4
#        with:
#          repository: Netcracker/qubership-core-bootstrap
#          path: core-bootstrap-repo
#
#      - name: Deploy cloud core
#        run: make -C core-bootstrap-repo/cloud-core-local-dev/ install

      - name: Run integration tests
        run: mvn clean test surefire-report:report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/reports'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4