name: Run Integration Tests

on:
  schedule:
    - cron: "*/5 * * * *"  # every minute
  workflow_dispatch:        # allows manual trigger too

concurrency:
  group: "integration-tests"
  cancel-in-progress: false

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run integration tests for all modules
        run: mvn -B clean surefire-report:report || true

      - name: Aggregate Surefire reports
        run: |
          for module in $(find . -type d -path "*/target/surefire-reports" | sed -E 's#/target/surefire-reports##' | sort -u); do
            modname=$(basename "$module")
            mkdir -p artifacts/$modname
            cp -r "$module/target/surefire-reports" artifacts/$modname/ || true
            if [ -d "$module/target/reports" ]; then
              cp -r "$module/target/reports" artifacts/$modname/ || true
            fi
          done

      - name: Upload all module artifacts
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: artifacts/*
