name: Run IT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kind-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kind
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Checkout Makefile repo
        uses: actions/checkout@v4
        with:
          repository: Netcracker/qubership-core-bootstrap
          path: core-bootstrap-repo

      - name: Run install target
        run: make -C core-bootstrap-repo/cloud-core-local-dev/ install

      - name: Run integration tests
        run: |
          echo "Running tests..."
          kubectl get nodes
          kubectl get pods -A
